### ISSUE TITLE
Discuss /list API endpoint

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations-registry#26]
Currently the `/list` API endpoint exposes all integrations packages. If there are multiple versions of one package (which is a normal case), it will expose all of them. But when thinking about it from an integrations manager specific view, the package that is of interest is the most recent one or the most recent one compatible with the current installations.

Questions:
* Should the `/list` API endpoint stay as is or only expose the most recent version?
* If we expose only 1 version, where are the other versions exposed? Should there be an API endpoint for an integration which exposes all the versions?

**Comment by ruflin** [comment]
@jasonrhodes @jfsiii Would be great to get your view on this from the integrations manager perspective.

**Comment by jfsiii** [comment]
> Should the /list API endpoint stay as is or only expose the most recent version?

Only returning the latest version works for the Manager. Especially because we're not supporting installing multiple versions in this initial phase.

> If we expose only 1 version, where are the other versions exposed? Should there be an API endpoint for an integration which exposes all the versions?

Yes, I think so. Ideally it would accept semver values or ranges (e.g. `1.2.3`, `1.x`, `^1.2.3`, `~1.2.3`, `'1.x || >=2.5.0 || 5.0.0 - 7.2.3'`, etc)

The two places that come to my mind are `/list` and `/package`. Some strawman interfaces:

- `/list?package=name&version=semver` returns list of `Package`s which match range
- `/package/versions/name` or `/package/versions/name?version=semver` returns list of versions (`[ '1.0.0', '1.0.1', '2.0.0-rc1' ]`)

**Comment by ruflin** [comment]
Will implement that the `/list` API only returns the most recent version. An later on, most recent which matches the query criteria when https://github.com/elastic/integrations-registry/issues/16 is implemented.

For the version list: Currently for the apache package we have the following endpoint: `/package/apache-1.0.1`. What if we would dedicated `/package/apache` to get the list of versions? And then we use what you suggest with `version=semver` for filtering: /package/apache?version=semver&compatibility=foo`. Optional a compatibility query could also be added here to only get the versions which are compatible with specific versions.

**Comment by ruflin** [comment]
Partially because of this conversation here, I realised we better call this endpoint `/search`: https://github.com/elastic/integrations-registry/pull/57

**Comment by ruflin** [comment]
Closing this for now as we don't have a direct need for it on the UI side.
