### ISSUE TITLE
Discuss: Template language to be used inside ingest pipelines

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations-registry#54]
Some of the ingest pipelines reference an other ingest pipeline. This is done through a template language as the name needs to be replaced with the actual name.

At the moment it looks as following:

```
"name": "{< IngestPipeline "pipeline-json" >}"
```

We need to decide which template language we should use when building the integrations so the integrations manager can replace these. Note: `mustache` is already used by Elasticsearch so templates might already contain mustache snippets which should not be replaced and we should not conflict with it.

**Comment by ruflin** [comment]
I quite like what you describe above with handlebars, especially that it lets us register our own helpers. This could become very handy.

One limitation of using mustache is that it's also used for example in search templates of Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html So assuming a package contains a search template with mustache / handlebar inside, this part we should not process. I guess the solution here could be to switch from `{{ ... }}` to `<< ... >>` or similar?

**Comment by willemdh** [comment]
@ruflin Sry for jumping in, but today I was looking for the 7.3.2 elasticsearch audit ingest pipelines, as I need to put those into our dedicated Stack monitoring cluster before updating our QA/PR cluster. (Because all the audit data is sent to Logstash which has some logic to drop access allowed's for system users)

When I tried to put the pipeline found in https://github.com/elastic/beats/blob/v7.3.2/filebeat/module/elasticsearch/audit/ingest/pipeline.json with Dev Tools

I noticed the json was invalid:

![image](https://user-images.githubusercontent.com/6462991/64946385-0b10cd80-d873-11e9-835f-b1291fa43e9a.png)

Not sure what the consequence is when inserted with Filebeat, but this doesn't seem very user friendly..? 

![image](https://user-images.githubusercontent.com/6462991/64946658-a2762080-d873-11e9-9919-31a5654fb7a2.png)

I guess for now I'll replace the " with a '..

```
      {
            "pipeline": {
                "if": "ctx.first_char != '{'",
                "name": "{< IngestPipeline 'pipeline-plaintext' >}"
            }
        },
        {
            "pipeline": {
                "if": "ctx.first_char == '{'",
                "name": "{< IngestPipeline 'pipeline-json' >}"
            }
        },
```

**Comment by willemdh** [comment]
Ok, when ingested with FIlebeat it appears to work fine.. Imho the whole ingest / template insertion design is handled the 'other way around'. Ingest pipelines and templates should be managed by Kibana if you'd ask me. There are many advantages to that approach.. It would lessen some of the privilege requirements for Beats users and would easy central management of templates and ingest pipelines..

**Comment by ruflin** [comment]
@willemdh Not sure how you ended up on this PR. But you will be happy to hear that the service that will pull the data from this registry will be Kibana. Solving the problems you mentioned above, is part of the goal of this project.

**Comment by willemdh** [comment]
@ruflin How I got here? Just imagine the following situation:

3 Clusters:
- Dedicated single Node Monitoring Cluster: MO => Contains elasticsearch server and audit logs of MO, QA and PR
- 12 node QA  Cluster: QA
- 12 node PR Cluster: PR

1) I need to update my clusters, say from 7.2.1 to 7.3.2. As I'm required to start with updating MO (otherwise QA cant index monitoring to MO). But on our MO node there is a Filebeat ingesting different kind of logs to PR (such as clamav, system, etc)
2) MO, QA and PR have a Filebeat indexing to Logstash PR which then indexes es audit and server  to MO, but system and clamav to PR
3) Our MO cluster needs the correct es audit pipelines of the new version asap. If this cluster does not contain the correct pipelines, cluster / logstash logs explode, as logstash tries to index to MO with @metadatapipeline which does not exist yet.
4) As I can't update a Filebeat yet ( as those index to PR...), I need to make sure the new audit and server pipelines exist on MO
5) So I try to find the correct pipelines in GitHub, though I found them here: https://github.com/elastic/beats/blob/v7.3.2/filebeat/module/elasticsearch/audit/ingest/pipeline.json
6) Importing with Dev Tools fails however, as the pipelines actually are not complete yet (as they contain for example `"name": "{< IngestPipeline 'pipeline-json' >}")`, which makes the json (and pipeline name) invalid..
7) As I started looking for  `"name": "{< IngestPipeline 'pipeline-json' >}")`, I didn't found a lot of meaningful results, except this thread..

Feel free to suggest a way to improve my update procedure..., as imho it's not very user/automation friendly atm..

**Comment by ruflin** [comment]
@willemdh I was more curious on how you found this issue as I don't think it's linked somewhere :-) 

There is no easy workaround for the above with the existing setup and is one of the reason for this project. Your manual approach is for now probably the one that works best. I hope the current templates are mostly self explanatory, but you need to replace it manually or use go template language.

**Comment by willemdh** [comment]
@ruflin Just google for `"{< IngestPipeline 'pipeline-json' >}"` :)

**Comment by ruflin** [comment]
For now I suggest we go with handlebars and see where we hit the limits. Closing this.

@willemdh One thing I just learned recently I wasn't aware can be used in ingest pipelines is the following:

```
      "pipeline": {
        "if": "ctx.agent?.version != null && ctx.event?.dataset == 'nginx.error'",
        "name": "filebeat-{{_ingest.agent.version}}-nginx-error-pipeline"
      }
```

It will make your pipeline a bit more dynamic.
